Consider the below code to answer further questions:


import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

Answer(Q1):

yes.There is difference in the data type of variables list_ and array_list.

list has str datatype elements, where as array_list has numpy.ndarray datatype elements

In [5]:
import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5' ]

array_list = np.array(object = list_)

print('data type of list_ ',type(list_))
print('data type of array_list ',type(array_list))     

data type of list_  <class 'list'>
data type of array_list  <class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and
array_list.

Answer(Q2):

In [10]:
for i in list_:
    print(type(i))
for j in array_list:
    print(type(j))    

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

Answer(Q3):

Yes.yes.There is difference in the data type of variables list_ and array_list. 

list has str datatype elements, where as array_list has numpy.int64 datatype elements


In [12]:
array_list = np.array(object = list_, dtype = int)
for i in list_:
    print(type(i))
for j in array_list:
    print(type(j))    

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:

(i)	 shape

(ii) size

In [30]:
import numpy as np
from functools import reduce 


num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)
# The shape of a list will be obtained using a module NumPy.
print(' Shape of num_list after converting to np array ',np.asarray(num_list).shape)
print(' Shape of num_array is ',num_array.shape)

print(' Size of num_list is ',reduce(lambda count, l: count + len(l), num_list, 0))
print(' Size of num_array is ',num_array.size)

 Shape of num_list after converting to np array  (2, 3)
 Shape of num_array is  (2, 3)
 Size of num_list is  6
 Size of num_array is  6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

Answer(Q5):


In [29]:
arr = np.zeros((3,3),dtype="int")
arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

Answer(Q6):


In [28]:
m1 = np.identity(5,dtype="int")
print(m1)
type(m1)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


numpy.ndarray